name: Deploy to Amazon ECS

on:
  push:
    branches: [ "master" ]

env:
  AWS_REGION: us-east-1                   # Replace with your AWS region
  ECR_REPOSITORY: my-ecr-repo             # Replace with your ECR repository name
  ECS_SERVICE: my-ecs-service             # Replace with your ECS service name
  ECS_CLUSTER: my-ecs-cluster             # Replace with your ECS cluster name
  ECS_TASK_DEFINITION: .aws/task-def.json # Replace with the path to your task definition JSON file
  CONTAINER_NAME: my-container            # Replace with your container name in task definition

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1 # Replace with your AWS region
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build -t my-app .
          docker tag my-app:latest <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-app:latest
          docker push <your-account-id>.dkr.ecr.us-east-1.amazonaws.com/my-app:latest

